# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Call for Submissions"
url = "calls/"
weight = 2


[[main]]
name = "Accepted Papers"
url = "papers/"
weight = 3


# [[main]]
# name = "Organizers"
# url = "organizers/"
# weight = 4


[[main]]
name = "Keynotes"
url = "speakers/"
weight = 4


# [[main]]
# name = "Panelist"
# url = "panel/"
# weight = 4
  
[[main]]
name = "Schedules"
url = "schedules/"
weight = 5
  
# [[main]]
# name = "Contact"
# url = "contact/"
# weight = 5


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

#[[footer]]
#name = "Blog"
#url = "blog/"
#weight = 2

#[[footer]]
#name = "Blog Details"
#url = "blog/post-1/"
#weight = 3

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 4